// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJhfBkfUftv423Em3GuZAxVtOHGAjmmI',
    appId: '1:217841718030:web:be87daebc5ccd41f8fbd5f',
    messagingSenderId: '217841718030',
    projectId: 'login-adb3d',
    authDomain: 'login-adb3d.firebaseapp.com',
    storageBucket: 'login-adb3d.appspot.com',
    measurementId: 'G-37K9ZQJBJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKC9vI0DQrGVmBmdyZfRaVUOsMxgVdlyw',
    appId: '1:217841718030:android:e1dc536a6334cfab8fbd5f',
    messagingSenderId: '217841718030',
    projectId: 'login-adb3d',
    storageBucket: 'login-adb3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyiY_eNxJwRS54iAYa4RqA2mUtmxV6ZaM',
    appId: '1:217841718030:ios:f79bdf7b526fc0ca8fbd5f',
    messagingSenderId: '217841718030',
    projectId: 'login-adb3d',
    storageBucket: 'login-adb3d.appspot.com',
    iosClientId: '217841718030-m4n61ag5sopslrqmijtsm582qrr63eaq.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.appEjercicio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyiY_eNxJwRS54iAYa4RqA2mUtmxV6ZaM',
    appId: '1:217841718030:ios:f41957b212c24ede8fbd5f',
    messagingSenderId: '217841718030',
    projectId: 'login-adb3d',
    storageBucket: 'login-adb3d.appspot.com',
    iosClientId: '217841718030-fmsjlf0pmg4deea6pa9fek3oqfv733qq.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.appEjercicio.RunnerTests',
  );
}
